[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 120

# Maximum session duration (2 minutes = 120 seconds) to control OpenAI costs
max_session_duration = 120

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = true

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = false

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = false
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

[features.audio]
    # Sample rate of the audio for voice mode
    sample_rate = 24000

[UI]
# Name of the assistant.
name = "Samantha"

# Description of the assistant. This is used for HTML tags.
description = "Ultimate AI Companion with Real-time Voice Interaction"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = false

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "full"

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
custom_css = "/public/anime-style.css"

# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file can be served from the public directory.
custom_js = "/public/anime-interface.js"

# Specify a custom font url.
custom_font = "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500;600;700&family=Inter:wght@300;400;500;600;700&display=swap"

# Specify a custom meta image url.
# custom_meta_image_url = "https://chainlit-cloud.s3.eu-west-3.amazonaws.com/logo/chainlit_banner.png"

# Specify a custom build directory for the frontend.
# This can be used to customize the frontend code.
# Be careful: If this is a relative path, it should not start with a slash.
# custom_build = "./public/build"

[UI.theme]
    default = "light"
    layout = "wide"
    font_family = "Noto Sans JP, Inter, sans-serif"

# Override default MUI light theme for Samantha's anime aesthetic
[UI.theme.light]
    background = "#667eea"
    paper = "#ffffff"

    [UI.theme.light.primary]
        main = "#ff6b9d"
        dark = "#e91e63"
        light = "#ff9ec3"
    [UI.theme.light.text]
        primary = "#1f2937"
        secondary = "#6b7280"

[meta]
generated_by = "2.5.5"

# Current settings for voice mode
max_response_output_tokens = 2048
temperature = 0.7

[theme]
primary_color = "#ff6b9d"
background_color = "#667eea"
text_color = "#1f2937"

[chatProfile]




