[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 120

# Maximum session duration (2 minutes = 120 seconds) to control OpenAI costs
max_session_duration = 120

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

[features]
# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = true

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = false

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = false
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

[features.audio]
    # Sample rate of the audio for voice mode
    sample_rate = 24000
    # Enable audio input/output
    enabled = true

[UI]
# Name of the assistant.
name = "Samantha Voice Assistant"

# Description of the assistant. This is used for HTML tags.
description = "AI Voice Companion with Real-time Conversation Capabilities"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = false

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "hidden"

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Custom CSS and JS are now embedded in chainlit.md for voice functionality
# custom_css = "/public/style.css"
# custom_js = "/public/sol-effects.js"

[meta]
generated_by = "2.5.5"




